#!/usr/bin/env bash

HELP="
NAME
  allsubdir - exceutes the specified command in all the sub directories of the working directory

USAGE
  allsubdir \"COMMAND_STRING\"

EXAMPLES
  allsubdir 'git pull'
  allsubdir 'igit log | grep luca | grep 2019.10.10'
"

function help {
  echo "$HELP"
}

if (( $# != 1 )); then
  help
  exit
fi

if [ "$1" = "--help" ] || [ "$1" = "-help" ] || [ "$1" = "-h" ]; then
  help
  exit
fi

for d in *; do (
  if [ -d "$d" ]; then
    cd "$d" && \
    dirname="$(pwd | sed 's|^.*/||g')"
    eval $1 2>&1 | sed 's/^/'"$dirname"': /g' && \
    echo
  fi
); done
