#!/usr/bin/env bash

# see https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode

blue="\033[00;34m"
reset="\033[00m"

echo -e "${blue}ATOM_HOME=/opt/alternative-home/atom++ atom $@ ${reset}\n";

ATOM_HOME=/opt/alternative-home/atom++ atom $@

# $ export ATOM_HOME=/opt/alternative-home/atom++
# $ apm list --installed --bare | sd '@.*' ''
# atom-beautify
# highlight-selected
# language-diff
# language-docker
# language-freemarker
# language-graphql
# language-ini
# language-nginx
# last-cursor-position
# linter-eslint
# markdown-cell-highlight
# markdown-preview-plus
# open-terminal-here
# simple-copy-path
# sort-lines
# teletype
