#!/usr/bin/env bash

# see https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode

blue="\033[00;34m"
reset="\033[00m"

echo -e "${blue}ATOM_HOME=/opt/alternative-home/atom_java atom $@ ${reset}\n";

ATOM_HOME=/opt/alternative-home/atom_java atom $@

# $ export ATOM_HOME=/opt/alternative-home/atom_java
# $ echo -e "apm install \\ \n $(apm list --installed --bare | sd '@.*' '' | sd '\n' ' \\\n ')"
# apm install \
# atom-ide-ui \
# ide-java \
