#!/usr/bin/env bash

# see https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode

blue="\033[00;34m"
reset="\033[00m"

echo -e "${blue}ATOM_HOME=/opt/alternative-home/atom_nodejs atom $@ ${reset}\n";

ATOM_HOME=/opt/alternative-home/atom_nodejs atom $@

# $ export ATOM_HOME=/opt/alternative-home/atom_nodejs
# $ echo -e "apm install \\ \n $(apm list --installed --bare | sd '@.*' '' | sd '\n' ' \\\n ')"
# apm install \
#  atom-beautify \
#  atom-ide-debugger-node \
#  atom-ide-ui \
#  busy-signal \
#  cucumber \
#  highlight-selected \
#  ide-typescript \
#  intentions \
#  language-diff \
#  language-docker \
#  language-freemarker \
#  language-graphql \
#  language-ini \
#  language-nginx \
#  last-cursor-position \
#  linter \
#  linter-eslint \
#  linter-ui-default \
#  markdown-cell-highlight \
#  markdown-preview-plus \
#  open-terminal-here \
#  simple-copy-path \
#  sort-lines \
#  teletype \
