#!/usr/bin/env bash

set -e # -e  exit immediately when a command fails

HELP="
NAME
  cbm - cargo binary manager

USAGE
  cbm <command>

Commands:
  list                          lists registered binaries
  upgrade                       installs/upgrades all the registered binaries
  verify                        checks the difference between what is installed and what it is registered
  register <crate> <bin> <desc> TODO registers a binary
  help                          shows this help
"

function help {
  echo "$HELP"
}

script_path="$(dirname $(realpath $0))"
#project_path="$(dirname $script_path)"

case $1 in
  list)
    (
      cd "$script_path/resources"
      awk -F ': ' '{print $2": "$3}' cargo.register | sort | column -s ':' -t
    )
  ;;
  upgrade)
    (
      cd "$script_path/resources"
      for crate in $(awk -F ': ' '{print $1}' cargo.register | sort); do
        echo -e "\nInstalling/upgradeing create ${crate}..."
        cargo install $crate
      done
    )
  ;;
  verify)
    (
      cd "$script_path/resources"
      diff <(awk -F ': ' '{print $2}' cargo.register | sort) <(ls ~/.cargo/bin) | rg '<|>' | sd '>' '+' | sd '<' '-'
    )
  ;;
  register)
    (
      cd "$script_path/resources"
      if [ -n "$2" ] && [ -n "$3" ] && [ -n "$4" ] && ! [[ -n "$5" ]]; then
        echo "$2: $3: $4 [REGISTERED]" >> cargo.register
        echo "$2: $3: $4 [REGISTERED]"
      else
        help
      fi
    )
  ;;
  *)
    help
  ;;
esac
