#!/usr/bin/env bash

if [[ -z "$1" || "$1" == "--help" ]]; then
  echo "
  SYNOPSY
  decode_file FILE_TO_DECODE [FILE_ENCODED]

  You can define and export the environment variable MYSECRET
  to encode /decode multiple files using the same password, e.g.:
  export MYSECRET=dontspeaktwice

  If the FILE_ENCODED parameter is not specified the output will
  be print on the stdout.
  "
  exit
fi

if [[ -z "${MYSECRET}" ]]; then
  if [[ -z "$1" ]]; then
    openssl aes-256-cbc -d -a -pbkdf2 -in "$1"
  else
    openssl aes-256-cbc -d -a -pbkdf2 -in "$1" -out "$2"
  fi
else
  if [[ -z "$1" ]]; then
    openssl aes-256-cbc -d -a -pbkdf2 -in "$1" -out "$2" -pass env:MYSECRET
  else
    openssl aes-256-cbc -d -a -pbkdf2 -in "$1" -pass env:MYSECRET
  fi
fi
