#!/usr/bin/env bash

if [[ -z "$2" ]]; then
  echo "
  SYNOPSY
  decode_file FILE_TO_DECODE FILE_ENCODED

  You can define and export the environment variable MYSECRET
  to encode /decode multiple files using the same password, e.g.:
  export MYSECRET=dontspeaktwice
  "
  exit
fi

if [[ -z "${MYSECRET}" ]]; then
  set -x # -x  print each command before executing it
  openssl aes-256-cbc -d -a -pbkdf2 -in "$1" -out "$2"
else
  set -x # -x  print each command before executing it
  openssl aes-256-cbc -d -a -pbkdf2 -in "$1" -out "$2" -pass env:MYSECRET
fi
