#!/usr/bin/env bash

if [[ -z "${SECRET}" ]]; then
  echo "
  You need to define and export the environment variable SECRET, e.g.:

  export SECRET=dontspeaktwice
  "
  exit
fi

echo $1 | openssl aes-256-cbc -d -a -pbkdf2 -pass env:SECRET
