#!/usr/bin/env bash

if [ -z "$1" ] || [ "$1" == "--help" ]; then
  echo "
  SYNOPSY
  decrypt_dir DIR_PATH

  You need to define and export the environment variable SECRET to use this utility,
  e.g.:
  export SECRET=dontspeaktwice
  "
  exit
fi

if [[ -z "${SECRET}" ]]; then
  echo "
  You need to define and export the environment variable SECRET to use this utility,
  e.g.:
  export SECRET=dontspeaktwice
  "
  exit
fi

key="$SECRET"
# TODO find a way to increase the key size

echo -e '\033[00;34m + xor --decrypt -k "$key" -r .\033[00m'
xor --decrypt -k "$key" -r .
