#!/usr/bin/env bash

if [ -z "$1" ] || [ "$1" == "--help" ]; then
  echo "
  SYNOPSY
  decrypt_dir DIR_PATH

  You need to define and export the environment variable SECRET to use this utility,
  e.g.:
  export SECRET=dontspeaktwice
  "
  exit
fi

if [[ -z "${SECRET}" ]]; then
  echo "
  You need to define and export the environment variable SECRET to use this utility,
  e.g.:
  export SECRET=dontspeaktwice
  "
  exit
fi

key="$SECRET"
# increase the key size
# WARNING do not increase it too much,
# otherwise setting the bash variable will throw "Argument list too long".
# This error will not block the script and it will set the variable to an empty string.
while [[ ${#key} -le 64000 ]]; do
  key="$(encode "$key" | tr '\n' ' ' | sed 's/[ =]//g')"
done
echo -e "\033[00;34m - #key=${#key}\033[00m"

echo -e '\033[00;34m + xor --decrypt -k "$key" -r .\033[00m'
xor --decrypt -k "$key" -r .
