#!/usr/bin/env bash

if [ -z "$1" ] || [ "$1" == "--help" ]; then
  echo "
  SYNOPSY
  decrypt_dir DIR_PATH

  You need to define and export the environment variable SECRET to use this utility,
  e.g.:
  export SECRET=dontspeaktwice
  "
  exit
fi

if [[ -z "${SECRET}" ]]; then
  echo "
  You need to define and export the environment variable SECRET to use this utility,
  e.g.:
  export SECRET=dontspeaktwice
  "
  exit
fi

decrypted="$(fd | xargs file -b | rg -v '^data$|^directory$' | wc -l)"
if ((decrypted > 0)); then
  echo -e "\033[00;34m The folder contains $decrypted file(s) that are not of type data."
  echo -e '\033[00;34m Skipping decryption\033[00m'
  echo -e '\033[00;34m Terminated\033[00m'
  exit
fi

if key="$(increaseKeyLenght "$SECRET" 128000)"; then
  # increaseKeyLenght completed successfully
  echo -e '\033[00;34m + xor --decrypt -k "$key" -r .\033[00m'
  xor --decrypt -k "$key" -r .
else
  # print the error
  echo "$key"
fi
