#!/usr/bin/env bash

set -e # -e  exit immediately when a command fails


if [[ -z "$2" ]]; then
  echo "
  SYNOPSY
  encode_file FILE_TO_ENCODE FILE_ENCODED

  You can define and export the environment variable SECRET
  to encode /decode multiple files using the same password, e.g.:
  export SECRET=dontspeaktwice
  "
  exit
fi

if [[ -z "${SECRET}" ]]; then
  (
    set -x # print each command before executing it
    openssl aes-256-cbc -a -salt -pbkdf2 -in "$1" -out "$2"
  )
else
  (
    set -x # print each command before executing it
    openssl aes-256-cbc -a -salt -pbkdf2 -in "$1" -out "$2" -pass env:SECRET
  )
fi
