#!/usr/bin/env bash

if [[ -z "${SECRET}" ]]; then
  echo "
  You need to define and export the environment variable SECRET, e.g.:

  export SECRET=don@t@speak@twice
  "
  exit
fi

echo $1 | openssl aes-256-cbc -a -salt -pbkdf2 -pass env:SECRET
