#!/usr/bin/env bash

set -e # -e  exit immediately when a command fails

if [ -z "$1" ] || [ "$1" == "--help" ]; then
  echo "
  SYNOPSY
  encrypt_dir DIR_PATH

  You need to define and export the environment variable SECRET to use this utility,
  e.g.:
  export SECRET=dontspeaktwice
  "
  exit
fi

if [[ -z "${SECRET}" ]]; then
  echo "
  You need to define and export the environment variable SECRET to use this utility,
  e.g.:
  export SECRET=dontspeaktwice
  "
  exit
fi

key="$SECRET"
# TODO find a way to increase the key size

echo -e '\033[00;34m + xor --force -k "$key" -r .\033[00m'
xor --force -k "$key" -r .
