#!/usr/bin/env bash

blue="\033[00;34m"
reset="\033[00m"

echo -e "${blue}executing '$@' using '/opt/alternative-home/home_flowtype' as home directory${reset}\n";

HOME=/opt/alternative-home/home_flowtype $@
