#!/usr/bin/env bash

set -e # exit if a commands returns a non-zero value

blue="\033[00;34m"
red="\033[00;31m"
reset="\033[00m"

error() {
  echo -e "${red}[error] $1${reset}";
}

info() {
  echo -e "${blue}[info] $1${reset}";
}

HELP="

USAGE:

  igit <ACTION> [OPTIONS]

ACTIONS:

  status
    shows the git status, the stash list and the unmerged branches

  pull
    pull the changes, shows the git status, the stash list and the unmerged branches

  push <message>
    pull, commit and push

  log [search pattern]
    if text-filter is not specified logs the lasts 60 commits,
    otherwise show all the commits that matches the given pattern

  diff [git diff options]
    shows the diffs using Meld

  mr <new commit/branch name>
    commits and pushes the staged changes to a new branch

  stash-unstaged <stash name>
    stashes the unstaged changes

  checkout <branch name>
    stashes the local changes, checkouts the branch, updates it and pop the stash

  restore <file/directory>
    restore the specified file/directory to the original content

  apply <file.patch>
    applies the specified patch

  list <type> [-1]
    <type> list file that has been:
            ?, untracked
            A, added
            M, modified
            D, deleted
    -1      list one file per line

  help
    show this help
"

help () {
  echo "$HELP"
}

wrong_syntax () {
  error "wrong syntax"
  help
  exit 1
}

status() {
  info "git status -sb"
  git status -sb
  info "git cherry -v # lists local commits that require a push"
  git cherry -v
  info "git stash list"
  git stash list
  info "git branch"
  git branch
}

pull() {
  info "git pull"
  git pull
  status
  info "git fetch --dry-run --prune # list removed branches"
  removed=$(git fetch --dry-run --prune 2>&1)
  if [ -n "${removed}" ]; then
    info "Removed branches:\n${removed}"
    read -p "Clean up removed branches? (y/n, default n) " yn
    if [ "$yn" = "y" ]; then
      info 'git fetch --prune'
      git fetch --prune
    fi
  fi
}

push() {
  if [ -z "$1" ]; then # if $1 is empty
    error "you need to specify the commit message"
    exit 1
  fi

  info "git pull && git commit -m "'"'"$1"'"'" && git push"
  git pull && git commit -m "$1" && git push
  info "git status"
  git status
}

log() {
  if [ -z "$1" ]; then # if $1 is empty
    info "git log --format='%ad %h %aE %s' --date='format:%Y.%m.%d %H:%M' --max-count=60 | grep -v 'Merge' | tac"
    git log --format='%ad %h %aE %s' --date='format:%Y.%m.%d %H:%M' --max-count=60 | grep -v 'Merge' | tac
  else
    info "git log --format='%ad %h %aE %s' --date='format:%Y.%m.%d %H:%M'  | grep -e \"$1\" | grep -v 'Merge' | tac"
    git log --format='%ad %h %aE %s' --date='format:%Y.%m.%d %H:%M'  | grep -e "$1" | grep -v 'Merge' | tac
  fi
}

diff() {
  info "git difftool --tool=meld --dir-diff $@"
  git difftool --tool=meld --dir-diff $@;
}

mr() {
  # if $1 is empty print the help and exit
  if [ -z "$1" ]; then wrong_syntax; fi

  commit="$1"
  branch="$(echo $1 | sd ' ' '-')"
  info "git checkout -b $branch" && \
  git checkout -b $branch && \
  info "git commit -m $commit" && \
  git commit -m "$commit" && \
  info "git push --set-upstream origin $branch" && \
  git push --set-upstream origin $branch;
}

stash_unstaged() {
  # if $1 is empty print the help and exit
  if [ -z "$1" ]; then wrong_syntax; fi

  path="$1"
  info "git commit -m 'temp'" && \
  git commit -m 'temp' && \
  info "git stash save \"$1\"" && \
  git stash save "$1" && \
  info "git reset HEAD^1" && \
  git reset HEAD^1 && \
  info "git add ." && \
  git add .
}

checkout() {
  # if $1 is empty print the help and exit
  if [ -z "$1" ]; then wrong_syntax; fi

  branchName="$1"
  info "git stash" && \
  git stash && \
  info "git checkout $branchName" && \
  git checkout $branchName && \
  info "git pull" && \
  git pull && \
  info "git stash pop" && \
  git stash pop
}

restore() {
  # if $1 is empty print the help and exit
  if [ -z "$1" ]; then wrong_syntax; fi

  paths="$@"
  info "git reset HEAD $paths" && \
  git reset HEAD $paths && \
  info "git add $paths" && \
  git add $paths && \
  info "git reset HEAD $paths" && \
  git reset HEAD $paths && \
  info "git checkout $paths" && \
  git checkout $paths
}

apply() {
  # if $1 is empty print the help and exit
  if [ -z "$1" ]; then wrong_syntax; fi

  patch_file="$1"
  info "git apply --3way --ignore-space-change --ignore-whitespace \"$patch_file\"" && \
  git apply --3way --ignore-space-change --ignore-whitespace "$patch_file"
}

list() {
  # if $1 is empty print the help and exit
  if [ -z "$1" ]; then wrong_syntax; fi

  case "$1" in
    "untracked" | "?")
      if [ "$2" = "-1" ]; then
        git status -sb | grep '^[?][?] ' | sed -r 's/.. "?([^"]*)"?/"\1"/g'
      else
        git status -sb | grep '^[?][?] ' | sed -r 's/.. "?([^"]*)"?/"\1"/g' | tr '\n' ' '
        echo ""
      fi
      ;;

    "added" | "A")
      if [ "$2" = "-1" ]; then
        git status -sb | grep '^A  ' | sed -r 's/.. (.*)/\1/g'
      else
        git status -sb | grep '^A  ' | sed -r 's/.. (.*)/\1/g' | tr '\n' ' '
        echo ""
      fi
      ;;

    "modified" | "M")
      if [ "$2" = "-1" ]; then
        git status -sb | grep '^ M ' | sed -r 's/.. (.*)/\1/g'
      else
        git status -sb | grep '^ M ' | sed -r 's/.. (.*)/\1/g' | tr '\n' ' '
        echo ""
      fi
      ;;

    "deleted" | "D")
      if [ "$2" = "-1" ]; then
        git status -sb | grep '^ D ' | sed -r 's/.. (.*)/\1/g'
      else
        git status -sb | grep '^ D ' | sed -r 's/.. (.*)/\1/g' | tr '\n' ' '
        echo ""
      fi
      ;;
    *)
      wrong_syntax
      ;;
  esac
}

case "$1" in
  "status")
    status ;;
  "pull")
    pull ;;
  "push")
    push "$2" ;;
  "log")
    log "$2" ;;
  "diff")
    diff ${@:2} ;;
  "mr")
    mr "$2" ;;
  "stash-unstaged")
    stash_unstaged "$2" ;;
  "checkout")
    checkout "$2" ;;
  "restore")
    restore ${@:2} ;;
  "apply")
    apply "$2" ;;
  "list")
    list "$2" "$3" ;;
  "h"|"-h"|"help"|"--help")
    help ;;
  *)
    wrong_syntax ;;
esac
