#!/usr/bin/env bash

if [ -z $SNIPPETS_HOME ]; then
  SNIPPETS_HOME=~/projects/my/snippets
else
  SNIPPETS_HOME=$(echo $SNIPPETS_HOME | sd '^~' "$HOME")
fi

if [ -z $IDE ]; then
  IDE=pulsar
fi

if [ -z $TUI_EDITOR ]; then
  TUI_EDITOR=hx
fi

HELP='

USAGE:

    snippets [ACTION] [search_pattern]

ACTIONS:

  fd, find
    searches and lists all the snippets with a name that matches the pattern

  rg, grep
    uses rg to grep the text inside all the snippets

  s, show
    shows all the snippets with a name that matches the pattern

  c, clip
    copies in the clipboard the first snippet with a name that matches the
    pattern

  e, edit
    opens the first snippet with a name that matches the pattern in the
    Helix editor

  a, all
    opens all the snippets with a name that matches the pattern in the
    Pulsar editor

  o, open
    opens the root folder of the snippets using the Pulsar editor

  h, help
    shows this help

EXAMPLES:

  # Lists all the file and folders
  snippets fd ".*"

  # Greps the word "bash" in all the files
  snippets rg "env bash"

  # Show all the snippets that contains "move to"
  snippets show "move to"

  # Edit (using helix) the first snippet that is a json (.json) and with a name
  # that contains "message"
  snippets edit -e json "message"

  # Edit (using lapce) all the snippets type json (the extension is .json)
  snippets all -e json ".*"

  # opens the root folder of the snippets using the Atom editor
  snippets open

DEPENDENCIES:

  fd - https://github.com/sharkdp/fd
  rg - https://github.com/BurntSushi/ripgrep
  hx - https://github.com/helix-editor/helix
  pulsar - https://github.com/pulsar-edit/pulsar
  xclip - sudo apt install xclip
  bat - https://github.com/rivy/rust.bat

  The root folder that contains all the snippets must be located at
  ~/projects/my/snippets, to change the path of the root folder set the
  environment variable SNIPPETS_HOME.

  The default IDE is pulsar, to change it set the environment variable IDE.

  The default terminal text editor is hx (Helix), to change it set the
  environment variable TUI_EDITOR.

'

case "$1" in
  "find" | "fd")
    fd ${@:2:$#-2} "${@: -1}" "$SNIPPETS_HOME"
  ;;
  "grep" | "rg")
    rg ${@:2:$#-2} "${@: -1}" "$SNIPPETS_HOME"
  ;;
  "show" | "s")
    #fd ${@:2:$#-2} "${@: -1}" "$SNIPPETS_HOME" -exec more
    fd --type f ${@:2:$#-2} "${@: -1}" "$SNIPPETS_HOME" --exec-batch bat --style=header --paging never
  ;;
  "clip" | "c")
    xclip -sel c -i "$(fd ${@:2:$#-2} "${@: -1}" "$SNIPPETS_HOME" | head -1)"
    bat "$(fd ${@:2:$#-2} "${@: -1}" "$SNIPPETS_HOME" | head -1)"
  ;;
  "edit" | "e")
    "$TUI_EDITOR" "$(fd ${@:2:$#-2} "${@: -1}" "$SNIPPETS_HOME" | head -1)"
  ;;
  "all" | "a")
    "$IDE" "$(fd ${@:2:$#-2} "${@: -1}" "$SNIPPETS_HOME" | head -1)"
  ;;
  "open" | "o")
  cd "$SNIPPETS_HOME"
  "$IDE" .
  ;;
  *)
    echo -e "$HELP"
  ;;
esac
