#!/bin/bash

set -e # exit if a commands returns a non-zero value

HELP="
suunto_report 1.0.0
Luca Pinelli

suunto_report builds and show a report of your free dives using the backup file
of the Suunto DM5 application (SQLite database).

USAGE:
  suunto_report BACKUP_FILE_PATH

ARGS:
  BACKUP_FILE_PATH the path of the backup file of the Suunto DM5 application
"

case "$1" in
  -h|--help)
    echo "$HELP"
    exit 0
esac

if [ -z "$1" ]; then
    echo "You need to specify a backup file"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "The file \"$1\" does not exist."
    exit 1
fi

type="$(file "$1")"
if [[ ! "$type" =~ "SQLite" ]]; then
    echo "The file \"$1\" is not a Suunto DM5 backup file (SQLite database)."
    exit 1
fi

if [[ ! "$1" =~ ".db.bak" ]]; then
    echo "The file \"$1\" does not have the correct extension: .db.bak"
    exit 1
fi

backup_name="$1"
db_file_name="$(echo "$backup_name" | sd '\.db.bak$' '.db')"
report_file_name="$(echo "$backup_name" | sd '\.db.bak$' '_report.txt')"

echo "> SQLite 3 Database: ${db_file_name}"
rm -f "$db_file_name"
cp "$backup_name" "$db_file_name"
file "$db_file_name"

echo '> create view "FreeDive"'
create_view="
create view FreeDive
as
select
  DiveId,
  cast(strftime('%Y', date(datetime(((StartTime / 10000000) - (1970 * 365 * 24 * 60 * 60) - (112 * 24 * 60 * 60)), 'unixepoch'))) as int) Year,
  cast(strftime('%m', date(datetime(((StartTime / 10000000) - (1970 * 365 * 24 * 60 * 60) - (112 * 24 * 60 * 60)), 'unixepoch'))) as int) Month,
  cast(strftime('%d', date(datetime(((StartTime / 10000000) - (1970 * 365 * 24 * 60 * 60) - (112 * 24 * 60 * 60)), 'unixepoch'))) as int) Day,
  cast(strftime('%W', date(datetime(((StartTime / 10000000) - (1970 * 365 * 24 * 60 * 60) - (112 * 24 * 60 * 60)), 'unixepoch'))) as int) Week,
  datetime(((StartTime / 10000000) - (1970 * 365 * 24 * 60 * 60) - (112 * 24 * 60 * 60)), 'unixepoch') DiveDate,
  Duration,
  (Duration / 60) || ':' || substr('0' || (Duration % 60), -2, 2) as ApneaTime,
  AvgDepth,
  MaxDepth,
  BottomTemperature as Temperature,
  DiveNumberInSerie as Serie
from dive
where mode = 3 --freedive
"
echo "$create_view" | bat --plain -l sql
sqlite3 "$db_file_name" "$create_view"

echo "
                               ╭─────────────────────╮
                               │ ╭─────────────────╮ │
                               │ │ FREEDIVE REPORT │ │
                               │ ╰─────────────────╯ │
                               ╰─────────────────────╯
"

print_graph () {
  rows=$1
  max=$2
  indentation=$3
  values=()
  for value in $rows; do
    scaled=$(eva "$value / $max * 48" | cut -d. -f1)
    values+=($scaled)
  done

  for j in 40 32 24 16 8 0; do
    echo -n "$indentation"
    for i in "${values[@]}"; do
      i=$(eva "$i-$j" | cut -d. -f1)
      if (( i <= 0 )); then
        echo -n " "
      else
        case $i in
          1) echo -n "▁" ;;
          2) echo -n "▂" ;;
          3) echo -n "▃" ;;
          4) echo -n "▄" ;;
          5) echo -n "▅" ;;
          6) echo -n "▆" ;;
          7) echo -n "▇" ;;
          *) echo -n "█" ;;
        esac
      fi
    done
    echo
  done

  echo -n "$indentation"
  for i in "${values[@]}"; do
    case $i in
      48) echo -n "*" ;;
      *) echo -n " " ;;
    esac
  done
  echo
}

best () {
  if [[ "$1" ==  "" ]]; then
    time=$(
      echo "
        select
          strftime('%Y-%m-%d', date(DiveDate)) DiveDay,
          ApneaTime,
          MaxDepth,
          Temperature
        from FreeDive
        order by ApneaTime desc, DiveDate
        limit 1
      " | sqlite3 "$db_file_name"
    )

    deep=$(
      echo "
        select
          strftime('%Y-%m-%d', date(DiveDate)) DiveDay,
          ApneaTime,
          MaxDepth,
          Temperature
        from FreeDive
        order by MaxDepth desc, DiveDate
        limit 1
      " | sqlite3 "$db_file_name"
    )

    echo "
    ╭──────╮
    │ Best │
    ╰──────╯

    $(echo "$time" | sd '(.*)\|(.*)\|(.*)\|(.*)' 'Time: ${1} ${2}, ${3} mt, ${4}°')
    $(echo "$deep" | sd '(.*)\|(.*)\|(.*)\|(.*)' 'Deep: ${1} ${2}, ${3} mt, ${4}°')
    "

  else
    time=$(
      echo "
        select
          strftime('%Y-%m-%d', date(DiveDate)) DiveDay,
          ApneaTime,
          MaxDepth,
          Temperature
        from FreeDive
        where year = $1
        order by ApneaTime desc, DiveDate
        limit 1
      " | sqlite3 "$db_file_name"
    )

    deep=$(
      echo "
        select
          strftime('%Y-%m-%d', date(DiveDate)) DiveDay,
          ApneaTime,
          MaxDepth,
          Temperature
        from FreeDive
        where year = $1
        order by MaxDepth desc, DiveDate
        limit 1
      " | sqlite3 "$db_file_name"
    )

    echo -n "
    ╭───────────╮
    │ Best ${1} │
    ╰───────────╯

    $(echo "$time" | sd '(.*)\|(.*)\|(.*)\|(.*)' 'Time: ${1} ${2}, ${3} mt, ${4}°')
    $(echo "$deep" | sd '(.*)\|(.*)\|(.*)\|(.*)' 'Deep: ${1} ${2}, ${3} mt, ${4}°')
    "

  fi
}

stats_per_year () {
  echo "
    ╭────────────────╮
    │ Stats per Year │
    ╰────────────────╯
  "
  echo ".mode columns
  select
    Year,
    count(distinct strftime('%Y-%m-%d', date(DiveDate))) '#days',
    count(*) '#dives',
    count(*) / count(distinct strftime('%Y-%m-%d', date(DiveDate))) '#dpd',
    cast(round(avg(MaxDepth)) as integer) avg_mt,
    cast(round(max(MaxDepth)) as integer) max_mt,
    cast(round(avg(Duration)) as integer) avg_s,
    cast(round(max(Duration)) as integer) max_s
  from FreeDive
  group by Year
  order by Year
  " | sqlite3 "$db_file_name" | sd '^' '    '
}

depth_hits () {
  echo "
    ╭────────────╮
    │ Depth Hits │
    ╰────────────╯
  "
  sql="$(
cat << EOF
.mode columns
select
  Year,
  Month,
  count(case when MaxDepth between 20 and 20.999 then 1 end) " 20 ",
  count(case when MaxDepth between 21 and 21.999 then 1 end) " 21 ",
  count(case when MaxDepth between 22 and 22.999 then 1 end) " 22 ",
  count(case when MaxDepth between 23 and 23.999 then 1 end) " 23 ",
  count(case when MaxDepth between 24 and 24.999 then 1 end) " 24 ",
  count(case when MaxDepth between 25 and 25.999 then 1 end) " 25 ",
  count(case when MaxDepth between 26 and 26.999 then 1 end) " 26 ",
  count(case when MaxDepth between 27 and 27.999 then 1 end) " 27 ",
  count(case when MaxDepth >= 28 then 1 end) " 28+ "
from freedive
where MaxDepth >= 20
group by Year, Month
union
select
  ' SUM' as Year,
  '' as Month,
  count(case when MaxDepth between 20 and 20.999 then 1 end) " 20 ",
  count(case when MaxDepth between 21 and 21.999 then 1 end) " 21 ",
  count(case when MaxDepth between 22 and 22.999 then 1 end) " 22 ",
  count(case when MaxDepth between 23 and 23.999 then 1 end) " 23 ",
  count(case when MaxDepth between 24 and 24.999 then 1 end) " 24 ",
  count(case when MaxDepth between 25 and 25.999 then 1 end) " 25 ",
  count(case when MaxDepth between 26 and 26.999 then 1 end) " 26 ",
  count(case when MaxDepth between 27 and 27.999 then 1 end) " 27 ",
  count(case when MaxDepth >= 28 then 1 end) " 28+ "
from freedive
where MaxDepth >= 20
order by Year, Month
EOF
  )"
  echo "$sql" | sqlite3 "$db_file_name" | sd '^' '    '
}

duration_hits () {
  echo "
    ╭───────────────╮
    │ Duration Hits │
    ╰───────────────╯
  "
  sql="$(
cat << EOF
.mode columns
select
  Year,
  Month,
  count(case when Duration between 110 and 111 then 1 end) "1:50",
  count(case when Duration between 112 and 113 then 1 end) "1:52",
  count(case when Duration between 114 and 115 then 1 end) "1:54",
  count(case when Duration between 116 and 117 then 1 end) "1:56",
  count(case when Duration between 118 and 119 then 1 end) "1:58",
  count(case when Duration between 118 and 119 then 1 end) "2:00",
  count(case when Duration between 118 and 119 then 1 end) "2:02",
  count(case when Duration between 118 and 119 then 1 end) "2:04",
  count(case when Duration >= 120 then 1 end) "2:06+"
from freedive
where Duration >= 110
group by Year, Month
union
select
  ' SUM' as Year,
  '' as Month,
  count(case when Duration between 110 and 111 then 1 end) "1:50",
  count(case when Duration between 112 and 113 then 1 end) "1:52",
  count(case when Duration between 114 and 115 then 1 end) "1:54",
  count(case when Duration between 116 and 117 then 1 end) "1:56",
  count(case when Duration between 118 and 119 then 1 end) "1:58",
  count(case when Duration between 118 and 119 then 1 end) "2:00",
  count(case when Duration between 118 and 119 then 1 end) "2:02",
  count(case when Duration between 118 and 119 then 1 end) "2:04",
  count(case when Duration >= 120 then 1 end) "2:06+"
from freedive
where Duration >= 110
order by Year, Month
EOF
  )"
  echo "$sql" | sqlite3 "$db_file_name" | sd '^' '    '
}

report () {

    echo "
    ╭───────────────╮
    │ Last 12 dives │
    ╰───────────────╯
    "

    echo ".mode columns
    select *
    from (
      select
        DiveDate,
        ApneaTime,
        MaxDepth 'Depth ',
        Temperature
      from FreeDive
      order by DiveDate desc
      limit 12
    )
    order by DiveDate
    " | sqlite3 "$db_file_name" | sd '^' '    '

    echo "
    ╭──────────────╮
    │ Last 12 days │
    ╰──────────────╯
    "

    echo ".mode columns
    select *
    from (
      select
        strftime('%Y-%m-%d', date(DiveDate)) DiveDay,
        max(ApneaTime) BestTime,
        max(MaxDepth) BestDepth,
        cast(round(avg(Temperature)) as integer) Temperature
      from FreeDive
      group by strftime('%Y-%m-%d', date(DiveDate)) -- DiveDay
      order by strftime('%Y-%m-%d', date(DiveDate)) desc -- DiveDay
      limit 12
    )
    order by DiveDay
    " | sqlite3 "$db_file_name" | sd '^' '    '

    echo "
    ╭──────────────╮
    │ Top duration │
    ╰──────────────╯
    "

    echo ".mode columns
    -- Daily Report: Top ApneaTime
    select DiveDate, ApneaTime, MaxDepth 'Depth ', Temperature, Serie
    from FreeDive
    join (
      select min(DiveId) id
      from FreeDive
      join (
        select strftime('%Y-%m-%d', date(DiveDate)) Day, max(Duration) Max
        from FreeDive
        group by strftime('%Y-%m-%d', date(DiveDate)) -- group by Day
        order by max(Duration) desc
      ) Top on Top.Day = strftime('%Y-%m-%d', date(DiveDate)) and Top.Max = Duration
      group by strftime('%Y-%m-%d', date(DiveDate))
      order by Duration desc
      limit 12
    ) TopRef where TopRef.id = DiveId
    order by Duration desc, DiveDate
    " | sqlite3 "$db_file_name" | sd '^' '    '

    echo "
    ╭───────────╮
    │ Top depth │
    ╰───────────╯
    "

    echo ".mode columns
    -- Daily Report: Top MaxDepth
    select DiveDate, ApneaTime, MaxDepth 'Depth ', Temperature, Serie
    from FreeDive
    join (
      select min(DiveId) id
      from FreeDive
      join (
        select strftime('%Y-%m-%d', date(DiveDate)) Day, max(MaxDepth) Max
        from FreeDive
        group by strftime('%Y-%m-%d', date(DiveDate)) -- group by Day
        order by max(MaxDepth) desc
      ) Top on Top.Day = strftime('%Y-%m-%d', date(DiveDate)) and Top.Max = MaxDepth
      group by strftime('%Y-%m-%d', date(DiveDate))
      order by MaxDepth desc
      limit 12
    ) TopRef where TopRef.id = DiveId
    order by MaxDepth desc, DiveDate
    " | sqlite3 "$db_file_name" | sd '^' '    '

    echo "
    ╭──────────────────────────────╮
    │ Monthly Report Best Duration │
    ╰──────────────────────────────╯
    "

    echo ".mode columns
    select TopRef.Month, ApneaTime, MaxDepth 'Depth ', Temperature, Serie
    from FreeDive
    join (
    	select min(Dive.DiveId) DiveId, TopTime.Month
    	from (
    		select strftime('%Y-%m', date(DiveDate)) Month, max(Duration) Max
    		from FreeDive
    		group by strftime('%Y-%m', date(DiveDate)) -- group by month
    	) TopTime
    	join FreeDive Dive on
    		strftime('%Y-%m', date(Dive.DiveDate)) = TopTime.Month
    		and Dive.Duration = TopTime.Max
    	group by TopTime.Month
    ) TopRef on TopRef.DiveId = FreeDive.DiveId
    order by Duration desc
    limit 12
    " | sqlite3 "$db_file_name" | sd '^' '    '

    echo "
    ╭───────────────────────────╮
    │ Monthly Report Best Depth │
    ╰───────────────────────────╯
    "

    echo ".mode columns
    select TopRef.Month, ApneaTime, MaxDepth 'Depth ', Temperature, Serie
    from FreeDive
    join (
    	select min(Dive.DiveId) DiveId, TopDepth.Month
    	from (
        select strftime('%Y-%m', date(DiveDate)) Month, max(MaxDepth) Max
        from FreeDive
        group by strftime('%Y-%m', date(DiveDate)) -- group by month
    	) TopDepth
    	join FreeDive Dive on
    		strftime('%Y-%m', date(Dive.DiveDate)) = TopDepth.Month
    		and Dive.MaxDepth = TopDepth.Max
    	group by TopDepth.Month
    ) TopRef on TopRef.DiveId = FreeDive.DiveId
    order by MaxDepth desc
    limit 12
    " | sqlite3 "$db_file_name" | sd '^' '    '

    echo "
    ╭────────────────────────╮
    │ Monthly Duration Graph │
    ╰────────────────────────╯
    "
    rows=`echo ".mode columns
    select max(Duration)
    from FreeDive
    group by Year, Month
    order by Year, Month
    " | sqlite3 "$db_file_name" | tail +3`
    max=`echo ".mode columns
    select max(Duration)
    from FreeDive
    " | sqlite3 "$db_file_name" | tail +3`
    print_graph "$rows" "$max" "    "

    echo "
    ╭─────────────────────────╮
    │ Monthly Max Depth Graph │
    ╰─────────────────────────╯
    "
    rows=`echo ".mode columns
    select max(MaxDepth)
    from FreeDive
    group by Year, Month
    order by Year, Month
    " | sqlite3 "$db_file_name" | tail +3`
    max=`echo ".mode columns
    select max(MaxDepth)
    from FreeDive
    " | sqlite3 "$db_file_name" | tail +3`
    print_graph "$rows" "$max" "    "

    echo "
    ╭─────────────────────────╮
    │ Monthly Avg Depth Graph │
    ╰─────────────────────────╯
    "
    rows=`echo ".mode columns
    select max(AvgDepth)
    from FreeDive
    group by Year, Month
    order by Year, Month
    " | sqlite3 "$db_file_name" | tail +3`
    max=`echo ".mode columns
    select max(AvgDepth)
    from FreeDive
    " | sqlite3 "$db_file_name" | tail +3`
    print_graph "$rows" "$max" "    "

    stats_per_year

    depth_hits

    duration_hits

    echo "
    ╭──────────────────╮
    │ +2 Minutes Dives │
    ╰──────────────────╯
    "
    echo ".mode columns
    select
      cast(round(MaxDepth) as integer) 'depth',
      sum(case when Year = 2024 then 1 else 0 end) '#2024',
      sum(case when Year = 2025 then 1 else 0 end) '#2025'
    from FreeDive
    where Duration >= 120
    group by cast(round(MaxDepth) as integer)
    order by cast(round(MaxDepth) as integer)
    " | sqlite3 "$db_file_name" | sd '^' '    '

    echo "
    ╭──────────────────╮
    │ +25 Meters Dives │
    ╰──────────────────╯
    "
    echo ".mode columns
    select
      cast(round(MaxDepth) as integer) 'depth',
      sum(case when Year = 2024 then 1 else 0 end) '#2024',
      sum(case when Year = 2025 then 1 else 0 end) '#2025'
    from FreeDive
    where round(MaxDepth) >= 25
    group by cast(round(MaxDepth) as integer)
    order by cast(round(MaxDepth) as integer)
    " | sqlite3 "$db_file_name" | sd '^' '    '

    best 2023
    best 2024
    best 2025
    best
}

report > "$report_file_name"

cat "$report_file_name"
