#!/usr/bin/env bash

set -e # exit immediately when a command fails

help="
NAME
  webcam_trust - setups the webcam on /dev/video4

USAGE
  webcam_trust [OPTION]

OPTION
  bw               Sets the webcam in black and white (saturation 100%)
  help,--help,-h   Shows this help

USAGE EXAMPLES
  webcam_trust
  webcam_trust bw
  webcam_trust help
"

configure_webcam () {
  if [ "$1" = "bw" ]; then
    set -x # print each command before executing it
    v4l2-ctl -d /dev/video4 -c saturation=1 # BW
  else
    set -x # print each command before executing it
    v4l2-ctl -d /dev/video4 -c saturation=32 # color
  fi

  v4l2-ctl -d /dev/video4 -c brightness=-64
  v4l2-ctl -d /dev/video4 -c contrast=24
  v4l2-ctl -d /dev/video4 -c hue=0
  v4l2-ctl -d /dev/video4 -c gain=0
  v4l2-ctl -d /dev/video4 -c sharpness=0
  v4l2-ctl -d /dev/video4 -c backlight_compensation=0
  v4l2-ctl -d /dev/video4 -c exposure_auto_priority=0
}


case "$1" in
  ""|"bw") configure_webcam "$1" ;;
  *) echo "$help" ;;
esac
