#!/usr/bin/env node

console.log('start');

const fs = require('fs');

const help=`
USAGE: printJestSnapshot [options]

OPTIONS:
  file      the path of the snapshot file (REQUIRED)

Examples:
1. printJestSnapshot file=./src/service/__snapshots__/processService.test.js.snap
2. printJestSnapshot file=./src/service/__snapshots__/processService.test.js.snap | xclip -selection clipboard
`

const getArg = (argName) => {
    const arg = process.argv.find(arg => arg.startsWith(argName + '='))
    if (!arg) {
        return null
    }
    return arg.substring(argName.length + 1)
}


const filePath = getArg('file')
if (!filePath || process.argv.find(arg => arg === 'help' || arg === '--help' || arg === '-help' || arg === '-h')) {
    console.log(help)
    process.exit()
}

const stdinBuffer = fs.readFileSync(filePath)
const snapshot = stdinBuffer.toString()

exports = {}

eval(snapshot)

const output = Object.entries(exports).map(([key, value]) => {
  return '\n-- ###### ' + key + ' ######\n\n' + value.substring(2, value.length - 2).replace(/\\/g, '')
}).join('\n')

console.log(output)
